<?php
    $title = 'Articolo';
    $description = 'Questa è una breve descrizione del contenuto della pagina per i motori di ricerca.';
    require_once('head.php');
?>
<article class="col-10 article">

    <h1 class="col-12 center">Il Monkey Island 3a di Ron Gilbert</h1>
    <h2 class="col-12 center subtitle">Mito o realtà?</h2>

<p class="col-12">Lucasdelirium non è mai stato un sito ossessionato dal "Monkey Island 3 che non è mai stato" di <A HREF="bio.php#gilbert" target=_blank>Ron 
Gilbert</A>: con il mai sopito riproporsi di questo tormentone videoludico, rinfocolato dall'uscita del retrò <A HREF="https://thimbleweedpark.com/">Thimbleweed Park</A>, penso sia il caso di riproporre la versione riveduta e corretta di questo articolo che scrissi nel 2013, pensato come aiuto concreto per capire il fenomeno.  Per chi si fosse perso le "puntate precedenti": Ron, dopo aver concluso nel 1992 <A HREF="monkey2.php" target=_blank>Monkey Island 2</A> in modo come sappiamo criptico con un finale molto ambiguo e spiazzante, lasciò la LucasArts <STRONG>di sua sponte</STRONG>. Poco dopo l'uscita di <A HREF="monkey3.php" target=_blank>The Curse of Monkey Island</A> (1997), terzo atto non gestito da lui, commentò che il gioco non gli era affatto dispiaciuto, anzi, ma che lui non avrebbe mandato avanti la storia in quel modo (e che "Elaine non avrebbe mai dovuto sposare Guybrush!"). Da allora fino ad oggi Gilbert, incalzato da giornalisti e fan, è più volte tornato sulla questione, risventolando il fantasma di un gioco mai fatto, un terzo capitolo alternativo.</P>

<h4 class="col-12 paragraph-subtitle">La posizione ufficiale di Ron</h4>

<p class="col-12">Tendenzialmente difendo Ron davanti ai fan che non ne possono più: penso che come autore sia difficile digerire che qualcun altro metta le mani sul tuo materiale, e che fosse un suo diritto esprimere pareri (o recriminazioni) sull'argomento. Di solito sono i fan e i giornalisti che tornano su questa storia, e lui risponde. C'è stata però una volta, proprio nel 2013, che ha preso l'iniziativa pubblicando <A HREF="http://grumpygamer.com/5777333" target=_blank>un articolo sul suo blog</A> in cui ipotizza come potrebbe essere il suo benedetto <EM>Monkey Island 3a</EM>. Riassumo.</P>
<ul class="col-12">
<li class="col-12">1 - Avrebbe grafica retrò con i pixelloni ma visualizzata con le capacità di rendering ed effetti attuali.</li>
<li class="col-12">2 - Non offirerebbe nessun aiuto e nessuna semplificazione degli enigmi, tutto sarebbe bello frustrante e hardcore.</li> 
<li class="col-12">3 - Presenterebbe su schermo gli oggetti dell'inventario ma non i verbi.</li>
<li class="col-12">4 - Sarebbe disponibile anche scatolato.</li>
<li class="col-4">5 - Ci sarebbero puzzle basati sui dialoghi.</li></ul>
<p class="col-2"></P>
<div class="col-12 no-margin">
<p class="col-8">
    <iframe src="https://www.youtube-nocookie.com/embed/zRmh1aFHHQQ" target=_blank width="640" height="360"></iframe></P></div>
<p class="col-2"></P>
<ul class="col-12">
<li class="col-12">6 - Funzionerebbe con un linguaggio come lo SCUMM, che programmerebbe per l'occasione.</li>
<li class="col-12">7 - Lo farebbe con un piccolo team, meno di dieci persone.</li> 
<STRONG><li class="col-12">8 - Lo farebbe solo se possedesse il marchio, nemmeno su licenza, perché "ha passato troppo tempo della sua vita a lavorare su cose che appartengono ad altri".</STRONG></li>
<li class="col-12">9 - Non ostacolerebbe i fan game ma li promuoverebbe, a patto che indicassero chiaramente di non essere canone.</li>
<li class="col-12">10 - S'intitolerebbe "Monkey Island 3a" e riprenderebbe dalla fine del secondo, perché per lui tutto ciò che viene dopo Monkey 2 non esiste (se ne scusa con gli autori dei seguiti e con chi li ha amati).</li>
<li class="col-12">11 - Non sarebbe lo stesso Monkey Island 3 che avrebbe fatto nel 1992, perché lui non è più la stessa persona.</li>
<li class="col-12">12 - Non sarebbe mandato in anticipo alla stampa per le recensioni.</li>
<li class="col-12">13 - Sarebbe tutto doppiato.</li>
<li class="col-12">14 - Se finanziato tramite Kickstarter, non sarebbe promosso con nessun premio particolare o video a effetto, e potrebbero passare anche lunghissimi periodi di tempo senza aggiornamenti durante l'eventuale lavorazione.</UL>
<p class="col-12">Dopo l'uscita di <A HREF="https://thimbleweedpark.com/" target=_blank>Thimbleweed Park</A>, abbiamo avuto un'importante conferma tangibile da Ron: ha dimostrato di potere eseguire al meglio i punti 1, 2, 5, 6, 7 e 13 in quest'epoca. Chapeau. Grazie a <EM>Thimbleweed Park</EM>, un nuovo <EM>Monkey Island</EM> di Gilbert con queste coordinate non sembra una forzatura nel percorso di freschezza che ha sempre seguito, come invece ci apparve quattro anni fa, alla pubblicazione di questa lista.<BR>
Rimane una questione fondamentale: il miraggio del suo "Monkey Island 3a", come ama scherzosamente chiamarlo, rischia di diventare poco più di un amaro sfogo, per via di un punto fondamentale che si perde nell'elenco, quello che ho posto in grassetto: lui non vuole lavorare chiedendo <STRONG>la licenza</STRONG> di Monkey Island alla Disney (come fecero i Telltale quando la chiesero alla LucasArts per <A HREF="tomi.php" target=_blank>Tales of Monkey Island</A>), lui vuole <STRONG>possedere</STRONG> il marchio! Campa cavallo. Ammesso e non concesso che la Disney voglia privarsene (mica hanno bisogno di soldi), istigare orde di fan è la maniera migliore per precludersi tale strada: se la Disney realizza che c'è mercato per un gioco del genere, a maggior ragione non si priva dei diritti e si limita a una licenza. E se anche volesse venderne i diritti, quanto diavolo costerebbe? E' così ingenuo da non temere l'eventuale cifra? Non credo, perché <STRONG>quel post non è un annuncio</STRONG>.</P>


<h4 class="col-12 paragraph-subtitle">Di chi è Monkey Island?</h4>


<p class="col-12">Questo dilemma si sarà riproposto innumerevoli volte nella storia delle proprietà intellettuali e dei marchi: chi ha diritto di dire dove debba andare a parare un marchio? Colui che l'ha creato o colui che ne ha reso possibile l'esistenza effettiva, registrandolo? A chi è più corretto che appartenga una proprietà intellettuale? Se ci mettessimo a decidere chi ha ragione, i legulei o i nostri eroi, la questione cadrebbe qui, parteggeremmo tutti a scatola chiusa per i designer a cui siamo affezionati. Però ci sono delle altre sensibilità da tenere in conto: quelle di coloro che hanno dato il loro contributo alla saga quando il suo creatore, per un motivo o per l'altro, non l'ha fatto. Un ex della LucasArts fu abbastanza politicamente scorretto da sbroccare davanti a quella lista di Ron.<BR>
Si tratta di <A HREF="http://www.mobygames.com/developer/sheet/view/developerId,2923/" target=_blank>Chuck Jordan</A>, che di <EM>Curse of Monkey Island</EM> fu coprogrammatore e codialoghista: ai Telltale dal 2007 al 2010, è stato fondamentale nel <A HREF="devil.php" target=_blank>ritorno in forma di Sam & Max</A>. Ecco come <A HREF="https://twitter.com/spectrecollie/status/324197855818559488" target=_blank>fece il verso a Ron</A> in Twitter:</P>
<blockquote class="col-12">"Col massimo rispetto per i team di talento che ci hanno lavorato, sono quindici anni che dico quanto avrei potuto far meglio di loro."</blockquote>
<p class="col-12">Inevitabile che degli utenti scattassero a difesa di Ron, ma occhio: Chuck non voleva sputare nel piatto in cui ha mangiato. Nel <A HREF="http://www.spectrecollie.com/archives/2013/04/shadows-of-the-empire" target=_blank>suo blog</A> ricordò come entrò alla LucasArts:</P>
<blockquote class="col-12">L'ho detto altre volte, ma <A HREF="monkey1.php" target=_blank>The Secret of Monkey Island</A> è stato il gioco che mi ha fatto cambiare indirizzo di studi: mi mostrò che i giochi potevano essere un mezzo efficace per raccontare storie, non solo un passatempo. Comprai subito tutti i giochi che riuscissi a trovare della LucasArts. Quasi immediatamente dopo aver finito <A HREF="ft.php" target=_blank>Full Throttle</A>, decisi che non potevo più resistere e mandai un curriculum alla cieca. Ero al settimo cielo quando ottenni il colloquio. Mi portarono allo Skywalker Ranch, mi mostrarono con nonchalance le teche contenenti il braccio di C3PO e il Santo Graal. Mi dissero che il colloquio era per lavorare su un seguito di Monkey Island, e a quel punto mi si chiuse lo stomaco e mi sentii praticamente svenire.</blockquote></P>
<p class="col-12">Riguardo alla sua uscita polemica contro Gilbert, Jordan espanse il concetto proprio nei commenti di tale post:</P>

<blockquote class="col-12">Per quanto riguarda la faccenda dei fan prigionieri nel passato, siano essi la maggioranza o solo una minoranza non silenziosa, c'è una cocciutaggine asinina con cui sono contento di non avere a che fare. Io stesso posso spesso lasciarmi andare al nerd fanboy che c'è in me per un sacco di cose, e mi faccio sentire se non mi piacciono. Ma tutti quelli che dicono stronzate come "il vero o falso Monkey Island 3 a seconda dei punti di vista", parlando di un gioco uscito nel 1997, davvero devono farsene una ragione. Questa cosa mi ferì all'epoca, ma dopo quindici anni di ossessione è una noia. E' per quello che, quando i Telltale stavano facendo il loro Monkey Island, chiesi di lasciarmene il più possibile lontano. Avevo già dato. Che i sedicenti fan spolpino l'osso e sognino un gioco che sarà sempre perfetto perché non esisterà mai. E' una cosa che personalmente mi ha rovinato il fandom di Monkey Island, quindi se lo possono tenere.</blockquote>

<div class="col-12 no-margin">
<p class="col-2"></p><figure class="col-8 center lightbox"><a href="img/monkey3/monkey33g.jpg"><img src="img/monkey3/monkey33g.jpg" sizes="(min-width: 60em) 15vw, (min-width: 45em) 19vw, 70vw" title="" alt="" class="col-12 no-margin"></a></figure><p class="col-2"></p></div>

<p class="col-12">Wow. Non approvo i toni e le volgarità, ma la sostanza del discorso di Jordan ebbe il merito di "sbloccare" il dibattito come non era mai accaduto prima. Ricevuto il "messaggio" di Chuck, Gilbert gli rispose indirettamente (e molto civilmente) con un <A HREF="http://grumpygamer.com/9168384" target=_blank>altro post</A>.</p>

<blockquote class="col-12">Il mio "vorrei riprendere da dove ho lasciato, libero da pesi, in un parco di divertimenti" era da prendere alla lettera. La mia storia per Monkey Island 3a comincia due minuti dopo la fine di Monkey Island 2. "Libero da pesi" non significa che consideri Curse of Monkey Island un "peso", ma piuttosto che se (ipoteticamente) progettassi e (ipoteticamente) scrivessi Monkey Island 3a, vorrei essere libero di mandare la storia dove voglio senza sentirmi obbligato alla coerenza con i giochi successivi. Se mai sarò in grado un giorno di fare questo gioco, potremmo scoprire che si inserisce bene tra Monkey Island 2 e Curse of Monkey Island.</blockquote>
<p class="col-12">Assetati di luce, i fan cominciarono a fare ipotesi sulla trama basandosi sull'ultima frase. Ovviamente, Gilbert nei commenti ha subito rettificato, facendo ripiombare tutto nella classica nebbia.</p>
<blockquote class="col-12">Non ho mai detto che si inserirebbe tra MI2 e MI3, ho detto che POTREBBE. Manderei la storia dove voglio. Se venisse fuori coerente con Curse, fantastico. Se finisse per cancellare tutti gli altri giochi, fantastico lo stesso.</blockquote>
<p class="col-12">Ma i sequel spuri lo sono per davvero? Quanto dei primi due Monkey Island è Ron Gilbert, e quanto è Lucasfilm Games / LucasArts? La continuità della tradizione lucasiana in fondo la saga l'ha sempre avuta, quel marchio c'è stato sempre, anche sul <EM>Tales</EM> dei Telltale (che peraltro erano una costola di LucasArts). Chi ha avuto il suo imprinting guybrushiano con <EM>Curse</EM> usa quello come metro di paragone, segno che la gregarietà del titolo non è scontata. <BR>Ho parlato con diversi fan nei forum, e mi sono reso conto che, se i seguiti sono considerati spuri, ciò si deve anche molto al tormentone del "Monkey Island 3a" di Ron Gilbert. In fondo lui e i fan alimentano in parallelo la delegittimazione dei seguiti, ottenendo due risultati: Gilbert con ogni dichiarazione del genere ricollega il marchio Monkey Island a se stesso, possedendolo almeno "moralmente" (visto che legalmente non ce l'ha), mentre i fan hanno una valvola di sfogo per sognare una rettifica a tutto ciò che non hanno gradito nei vari sequel.</P>


<h4 class="col-12 paragraph-subtitle">Ma esiste un Monkey Island 3 di Ron Gilbert mai fatto?</h4>


<div class="col-12 no-margin"><p class="col-4">Il fatto stesso delle dimissioni di Ron dalla LucasArts all'apice della libertà creativa, per fondare un'azienda dedicata alle avventure per bambini, un attimo dopo aver terminato <EM>Monkey Island 2</EM>, non mi ha mai suggerito un'interruzione traumatica della meticolosa esecuzione di una saga.</p>
<figure class="col-8 center lightbox"><iframe src="https://www.youtube-nocookie.com/embed/fHC4VeAlJpU" target=_blank></iframe></figure></div>


<p class="col-12">In una recente intervista con <A HREF="https://www.youtube.com/watch?v=KgzWorfLjeE" target=_blank>Talks at Google</A>, Ron ricorda che non aveva idea del successo riscosso dai due Monkey Island in Europa: sapeva solo che la concorrenza Sierra li aveva stracciati ancora nelle vendite americane, quindi riteneva i suoi lavori prodotti ben accolti e nulla più. In una <A HREF="http://scummbar.com/resources/articles/index.php?newssniffer=readarticle&article=1031" target=_blank>vecchia intervista</A> risalente al post-Monkey 2 sembrava convinto di poterci un giorno lavorare, ma solo ipoteticamente:</p>
<blockquote class="col-12">Per quanto riguarda Monkey 3, dubito che sarò io a farlo <STRONG>se esisterà</STRONG>, ma non ho dubbi che vi sarò coinvolto in qualche maniera. Non è in produzione. Se tutto andasse come a me piacerebbe, sarei io il designer o codesigner del gioco.</blockquote>
<p class="col-12">Ingenuità di un ventiseienne. Il <EM>Monkey Island 3</EM> "alternativo" di Ron ha cominciato a prender forma nelle sue dichiarazioni proprio nel 1997, quando il mondo degli affari lo ha offeso, generando <EM>The Curse of Monkey Island</EM> senza prendersi la briga di coinvolgerlo, solo perché non faceva più parte dell'azienda. <EM>Monkey Island 3a</EM>, prima che <EM>Curse</EM> fosse realizzato, evidentemente non aveva alcuna necessità di essere discusso seriamente, ma da quel lontano 1997 è scattata una questione di principio, ingigantita ora dal timore comprensibile di vedere il marchio seppellito nei magazzini della Disney.<BR>
In un <A HREF="http://retronauts.libsyn.com/retronauts-vol-iv-episode-45-the-monkey-island-series-with-special-guest-ron-gilbert" target=_blank>podcast di Retronauts</A>, Gilbert ci dice che il finale di Monkey 2 non fu pensato così perché avesse intenzione di lasciare la LucasArts (rendendo la vita difficile a chi avesse fatto il terzo capitolo). <EM>"Semplicemente non avevo un finale."</EM> Nella sua testa Monkey Island era sì <STRONG>idealmente</STRONG> una trilogia, ma... <EM>"non avevo in realtà idea di cosa stessi facendo. Avevo un'idea molto vaga, ma continuavo a procrastinare. Il finale fu più che altro il risultato del puro panico, stavamo per chiudere il gioco e non avevo un finale. </EM>[conferma <STRONG>piena</STRONG> della <A HREF="download/finale.rtf" target=_blank>tesi</A> elaborata dal fan ATMachine nel 2007, ndDiduz]. </EM><BR>
In <A HREF="http://pastebin.com/XrL69Psy" target=_blank>uno streaming</A> di una partita a Monkey Island 2, organizzata sui forum della Double Fine, è ancora più esplicito:</p>
<blockquote class="col-12">Il finale mi mise in crisi per un bel po'. Venni folgorato una mattina mentre ero ancora a letto. <STRONG>Non voleva essere un cliffhanger.</STRONG></blockquote>
<p class="col-12">Aspettate, questa merita più risalto.</p>
<h1 class="col-12 center"><EM>"Non voleva essere un cliffhanger."</STRONG></EM></h1>
<p class="col-12">Mi capirete se dico che una frase del genere mi aveva fatto cascare alquanto le braccia: mi aveva fatto pensare che Monkey Island non fosse mai stata una trilogia scontata ("se esisterà"), rendendomi molto difficile delegittimare a priori <A HREF="monkey3.php" target=_blank>The Curse of Monkey Island</A>, <A HREF="monkey4.php" target=_blank>Fuga da Monkey Island</A> e <A HREF="tomi.php" target=_blank>Tales of Monkey Island</A>. Mettersi tuttavia il cuore in pace con questa storia del <EM>Monkey Island 3</EM> immaginario gilbertiano, scegliendo cosa pensare inequivocabilmente, è purtroppo impossibile. Mesi dopo l'uscita di <A HREF="tp.php">Thimbleweed Park</A>, qualcuno <A HREF="https://forums.thimbleweedpark.com/t/ron-gilbert-about-art-and-bad-endings/1686">sul forum del gioco</A> ha citato alcune frasi di Ron da una sua vecchia conferenza del PAX Australia 2013, precisamente queste:</p>
<blockquote class="col-12">Quel finale davvero crea opinioni molto divergenti, significa che quel finale ha significato qualcosa. Potrei averlo fatto con Guybrush ed Elaine che vivevano felici e contenti, ma nessuno avrebbe parlato di quel finale vent'anni dopo, nessuno mi avrebbe mandato email arrabbiate per dirmi quanto avesse gradito la felicità di Guybrush ed Elaine. [...]<BR>
Amo le foto dei gattini come chiunque altro, ma mi piace anche leggere, guardare o giocare cose che mi fanno fermare a pensare: "Ma che cazzo è successo?" Magari non voglio rivederle o rigiocarle, ma non riesco a smettere di pensarci.</blockquote>
<p class="col-12">La citazione ha riattivato per l'ennesima volta la conversazione sul tormentone dei tormentoni, e Ron è intervenuto spietato:</p>
<blockquote class="col-12"> 
Prima che la produzione di <A HREF="monkey1.php">The Secret of Monkey Island</A> terminasse, l'avevo pianificato come una trilogia. Non commettete l'errore di pensare che "Non avevo un finale" significasse non sapere quale dovesse essere il tema del finale e dove la storia generale dovesse andare a parare. E' così che va. Alcune persone vi diranno che devi avere un finale prima di cominciare, ma queste persone sbagliano e basta, non sono persone che creano cose interessanti. Parte del processo di scrittura consiste nel capire la tua storia. Quando stai per finire, ti rendi conto che non è la storia da cui eri partito. Se ora pensate che avessi l'intera trilogia di Monkey Island in testa dal primo giorno, rimarreste delusi. Sapevo a grandi linee i punti salienti della storia, ma tutto qui, nè mi aspetto che la maggior parte dei narratori abbia di più. Le idee sono guide, non sono una mappa nero su bianco, da seguire. E' un processo che si chiama creazione.</blockquote>
<p class="col-12">Insomma, chi di noi cerca razionalmente di smontare questo fantomatico <EM>Monkey Island 3 di Ron Gilbert</EM> viene messo a tacere. Non possiamo vincere. In forma nebulosa <STRONG>è sempre esistito</STRONG>. Io quindi mi arrendo, lascio la palla a voi. Mi levo però la soddisfazione di una considerazione: se davvero Ron ama i finali aperti e le spiegazioni nebulose o assenti, visionarie alla Lynch, come ha perfettamente dimostrato di amare anche in <EM>Thimbleweed Park</EM> e <A HREF="cave.php">The Cave</A>, l'idea stessa di proseguire oltre quel misterioso finale di <EM>LeChuck's Revenge</EM>, col rischio di <STRONG>spiegarlo</STRONG>, mi appare una forzatura non meno pesante dei sequel "spuri" pubblicati. A meno che Ron poi non voglia creare un terzo episodio che confonda le acque ancora di più: non lo escluderei nemmeno, però mi permetto di pensare che non sia esattamente quello che i fan si aspetterebbero...</p>

</article>
<?php 
    echo('<script>');
    if (isset($articleBannerImg) && isset($previousArticle) && isset($nextArticle)) {
        echo('articleBannerImg=\''.$articleBannerImg.'\';previousArticle=\''.$previousArticle.'\';nextArticle=\''.$nextArticle.'\';'.file_get_contents('js/article-banner-and-nav.js'));
    }
    echo(file_get_contents('js/generic-article.js').'</script>'); 
    require_once('footer.php');
?>
